### PR TITLE
Limit query commands, fix #21

### LINKED ISSUE #21: Suggestion: Return possible exposure range after setting framerate
i.e. return exposure range from `framerate!()`

It would help for setting interactive controls (sliders etc) or just doing limit checks

### PR DESCRIPTION
**Pull request by samuelpowell**
Allow query of the limits of high level numeric functions

### CODE REVIEW

**Comment by samuelpowell** [comment]
@ianshmean does this work for you?

**Comment by ianshmean** [comment]
Looks good! thanks.
Although, can't test until #19 is solved

**Comment by samuelpowell** [comment]
Okay, #19 down, how does this look @ianshmean ?

**Comment by samuelpowell** [comment]
@ianshmean rebased for your pleasure

**Pull request merged**
