### PR TITLE
Suggestion for non-fatal erroring when not built properly (i.e. SDK missing)

### PR DESCRIPTION
**Pull request by ianshmean**
There may be a better way to handle this. Open to review!

### CODE REVIEW

**Comment by ianshmean** [comment]
@samuelpowell Given the automerge requirement, it's probably worth enabling travis on this, to check for non-fatality

**Comment by samuelpowell** [comment]
Okay so does it work? If no Spinnaker found we quietly load but all functions will be broken and error at runtime?

**Comment by ianshmean** [comment]
Correct. 

After removing the spinnaker .dylib's temporarily:
```
(v1.3) pkg> build Spinnaker
  Building Spinnaker → `~/Documents/GitHub/Spinnaker.jl/deps/build.log`
 Resolving package versions...
[ Info: No changes

julia> using Spinnaker
[ Info: Precompiling Spinnaker [8e0d2ad3-56b8-53f3-8036-54b674872bef]
┌ Error: Package configuration file missing, run 'Pkg.build("Spinnaker")' to configure.
└ @ Spinnaker ~/Documents/GitHub/Spinnaker.jl/src/Spinnaker.jl:59

julia> CameraList()
ERROR: UndefVarError: libSpinnaker_C not defined
Stacktrace:
 [1] spinCameraListCreateEmpty at /Users/ian/Documents/GitHub/Spinnaker.jl/src/wrapper/spin_api.jl:201 [inlined]
 [2] CameraList() at /Users/ian/Documents/GitHub/Spinnaker.jl/src/CameraList.jl:16
 [3] top-level scope at none:0
```
I have a [PR open](https://github.com/JuliaLang/Pkg.jl/pull/1502/files) to clarify the `Info: No changes` message, as it's deceptive here, because build.jl did make changes to the build in this case.

**Comment by ianshmean** [comment]
It would be nice if we could print a soft error to REPL during the `build` stage, but I don't know if that's possible

**Comment by samuelpowell** [comment]
@ianshmean what's going on is this good to go?

**Comment by ianshmean** [comment]
Yeah. The only thing is that if you forget to install the Spinnaker SDK, it won't be obvious at install time given the error log goes straight to file in `deps/build.log`  rather than being printed.

I'm not aware of a better approach out there, so we should merge and keep an eye on best practice

**Comment by samuelpowell** [comment]
Does this match with what people do at the moment in other packages?

**Comment by ianshmean** [comment]
I based it on CuArrays or one of that family. It should be

**Pull request merged**
